spring.application.name=aiops-svm-service
server.port=9183

spring.datasource.url=jdbc:mysql://${DB_HOST:192.168.1.5}:${DB_PORT:3306}/XnetAIops?useSSL=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:000000}

mybatis.configuration.map-underscore-to-camel-case=true

logging.level.root=info
logging.level.com.synapxnet=debug
